#google cloud deployment -gke-prod.
apiVersion: v1
kind: Service
metadata:
  name: joiner-service
  annotations:
    # Expose prometheus metrics to collect
    prometheus.io/scrape: "true"
    prometheus.io/scheme: "http"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
    # Avalibility probe (default path is root)
    prometheus.io/probe: "true"
    prometheus.io/probe_path: "/actuator/info"
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: joiner-service
