#joiner-service configmap, gke-prod
apiVersion: v1
kind: ConfigMap
metadata:
  name: joiner-service-configmap
  namespace: markets-finland
data:
  kafka-bootstrap-servers: "10.200.8.5:9092,10.200.8.6:9092,10.200.8.7:9092"
  kafka-spp-source-topic: "spp_events"
  kafka-geco-source-topic: "game_tracking"
  kafka-destination-topic: "finland-veikkaus-player-events"
  kafka-application-id: "finland-veikkaus-joiner-service-gke-PROD"
  dry-run: "false"
  kafka-cleanup: "false"
  source-casinoids: "veikkaus"

